/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    Button: typeof import('./../components/Button.vue')['default']
    LeftMenu: typeof import('./../components/LeftMenu.vue')['default']
    NotFound: typeof import('./../components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VaAvatar: typeof import('vuestic-ui')['VaAvatar']
    VaIcon: typeof import('vuestic-ui')['VaIcon']
    VaInput: typeof import('vuestic-ui')['VaInput']
    VaList: typeof import('vuestic-ui')['VaList']
    VaListItem: typeof import('vuestic-ui')['VaListItem']
    VaListItemLabel: typeof import('vuestic-ui')['VaListItemLabel']
    VaListItemSection: typeof import('vuestic-ui')['VaListItemSection']
    VaListLabel: typeof import('vuestic-ui')['VaListLabel']
    WaveSvg: typeof import('./../components/WaveSvg.vue')['default']
  }
}
