/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/AppHeader/AppHeader.vue')['default']
    Button: typeof import('./../components/Button.vue')['default']
    LeftMenu: typeof import('./../components/LeftMenu.vue')['default']
    NotFound: typeof import('./../components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSelect: typeof import('./../components/AppHeader/ThemeSelect.vue')['default']
    Tree: typeof import('./../components/Tree/index.vue')['default']
    TreeItem: typeof import('../components/Tree/TreeNode.vue')['default']
    TreeNode: typeof import('./../components/Tree/TreeNode.vue')['default']
    TreeNodeContent: typeof import('./../components/Tree/TreeNodeContent.vue')['default']
    VaAvatar: typeof import('vuestic-ui')['VaAvatar']
    VaButton: typeof import('vuestic-ui')['VaButton']
    VaCheckbox: typeof import('vuestic-ui')['VaCheckbox']
    VaInput: typeof import('vuestic-ui')['VaInput']
    VaList: typeof import('vuestic-ui')['VaList']
    VaListItem: typeof import('vuestic-ui')['VaListItem']
    VaListItemLabel: typeof import('vuestic-ui')['VaListItemLabel']
    VaListItemSection: typeof import('vuestic-ui')['VaListItemSection']
    VaListLabel: typeof import('vuestic-ui')['VaListLabel']
    VaModal: typeof import('vuestic-ui')['VaModal']
    VaSelect: typeof import('vuestic-ui')['VaSelect']
    VaTextarea: typeof import('vuestic-ui')['VaTextarea']
    VaTreeView: typeof import('vuestic-ui')['VaTreeView']
    WaveSvg: typeof import('./../components/WaveSvg.vue')['default']
  }
}
