export const MorseMap = {
  '数字': {
    '0': '-----',
    '1': '.----',
    '2': '..---',
    '3': '...--',
    '4': '....-',
    '5': '.....',
    '6': '-....',
    '7': '--...',
    '8': '---..',
    '9': '----.',
  },
  '字母': {
    A: '.-',
    B: '-...',
    C: '-.-.',
    D: '-..',
    E: '.',
    F: '..-.',
    G: '--.',
    H: '....',
    I: '..',
    J: '.---',
    K: '-.-',
    L: '.-..',
    M: '--',
    N: '-.',
    O: '---',
    P: '.--.',
    Q: '--.-',
    R: '.-.',
    S: '...',
    T: '-',
    U: '..-',
    V: '...-',
    W: '.--',
    X: '-..-',
    Y: '-.--',
    Z: '--..',
  },
  '字符': {
    '?': '..--..',
    '/': '-..-.',
    '[': '-.-..',
    ']': '.---.',
    '-': '-....-',
    '.': '.-.-.-',
    '@': '--.-.',
    '*': '----',
    '$': '...-.',
    '#': '..--'
  }
} as const

export const explainToSecretMap: Record<string, string> = Object.values(MorseMap).reduce((obj, now) => Object.assign(obj, now), {})
export const secretToExplainMap: Record<string, string> = Object.keys(explainToSecretMap).reduce((obj, key) => Object.assign(obj, { [explainToSecretMap[key]]: key }), {})
